---
- name: install automysqlbackup
  apt: name=automysqlbackup state=latest
  when: backup_dir is defined

- name: apply automysqlbackup configuration
  sudo: yes
  template:
    src: automysqlbackup.j2
    dest: /etc/default/automysqlbackup
    group: root
    owner: root
    mode: 0600
  when: backup_dir is defined

- name: remove the cron.daily file
  sudo: yes
  file: path=/etc/cron.daily/automysqlbackup state=absent
  tags:
    - automysqlbackup
  when: backup_dir is defined

- name: add automysqlbackup cron job
  sudo: yes
  cron:
    name: "automysqlbackup"
    minute: "0"
    hour: "{{ backup_hour }}"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: "/usr/sbin/automysqlbackup"
  tags:
    - automysqlbackup
  when: backup_dir is defined


- name: install s3cmd
  sudo: true
  apt: name=s3cmd state=present
  when: backup_dir is defined

- name: configure s3cmd
  sudo: true
  template: >
    src=s3cfg.j2
    dest=/root/.s3cfg
  when: backup_dir is defined


