---
- name: create mysql config dir
  file:
    path: "{{ apps_config_dir }}/mysql"
    state: directory
    mode: 0755
- name: copy mysql config
  template: 
    src: my.cnf
    dest: "{{ apps_config_dir }}/mysql/my.cnf"
