---
- name: create login user
  user: 
    name: "{{ item.name }}"
    groups: "sudo"
    shell: "/bin/bash"
  with_items: "{{ ssh_users }}"

- name: 'add pubkey to login user'
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items: "{{ ssh_users }}"

- name: 'add login user to sudoers'
  lineinfile:
    dest: "/etc/sudoers"
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    regexp: '^{{ item.name }}'
    state: present
  with_items: "{{ ssh_users }}"
