---
- name: 'apt | update'
  apt: update_cache=yes cache_valid_time=3600

- name: 'install nginx'
  apt: name=nginx state=present

- name: remove default nginx vhost
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: copy nginx vhost
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/{{ name }}.conf
  notify: restart nginx

- name: configure web firewall
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: 'allow', port: '80', proto: 'tcp' }
    - { rule: 'allow', port: '443', proto: 'tcp' }
  notify:
    - restart ufw
